### ISSUE TITLE
Doesn't handle `keyof` and `typeof`

### ISSUE THREAD

**Issue by adrianheine** [marijnh/builddocs#12]
gettypes emits `keyof` and `typeof` with single `typeArgs`. Unless we want to add a generic type operator thing we need to hardcode them in the templates.

**Comment by marijnh** [comment]
I think the type param kludge is preferable to a separate property, since it is harder to accidentally 'drop' the operator by ignoring the property for it this way (i.e. in its current form, builddocs' output will at least convey the information that the operator is there, even if it should format it more TypeScript-like). But yeah, we should add a special case to the type template for these.

**Comment by adrianheine** [comment]
A generic thing could look like `{type: "operation", operator: "typeof", typeArgs: ["X"]}`. I'm still wondering if putting both user-defined types and syntax types in `type` is a good thing to do …

**Comment by marijnh** [comment]
It seemed like a convenient encoding for the above reasons, and because `typeOrigin=null` can be used to unambiguously distinguish these from user-defined types with the same names. But yeah, what you describe would use the fields in a somewhat more structured way, and if you want to move to that I'm fine with it too (I assume union/intersection would also follow that form?).

**Comment by adrianheine** [comment]
I tried it out, but it doesn't actually help, since the output for most operations (except single keyword operations) is specific.

**Comment by adrianheine** [comment]
Fixed in #15.
